version: "3.9"  # optional since v1.27.0
services:

  api:
    restart: unless-stopped
    build: .
    links:
      - "db:db"
    environment:
      - "MYSQL_HOST=db"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=neptunes

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8081:80"
    links:
      - "db:neptunes"